#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
#but for the 9th iteration, displays Hi
n=1
while [ $n -ne 11 ]; do
    if [ $n -eq 9 ]; then
        echo "Hi"
    else
        echo "Holberton School"
    fi
    let n+=1
done
