#!/usr/bin/env bash
# Bash script that loops from 1 to 20
# displays bad luck from China for the 4th loop iteration
# displays bad luck from Japan for the 9th loop iteration
# displays bad luck from Italy for the 17th loop iteration
n=0
while [ $n -ne 21 ]; do
    echo $n
    case "$n" in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
             echo "bad luck from Italy"
            ;;
    esac
    let n+=1
done
